MAIN_COLOR_DARK = "#374F77"
MAIN_COLOR_LIGHT = "#4473DE"
WARNING_COLOR = "#DE3232"
WARNING_COLOR_DARK = "#BC827A"

# MAIN_FONT_SIZE = 12
# MAIN_MID_FONT_SIZE = 16
# MAIN_LARGE_FONT_SIZE = 20
MAIN_SMALL_FONT_SIZE = 14
MAIN_FONT_SIZE = 18
MAIN_MID_FONT_SIZE = 20
MAIN_LARGE_FONT_SIZE = 22
MAIN_ULTRA_FONT_SIZE = 36

# MAIN_SMALL_FONT = 'helvetica {}'.format(MAIN_SMALL_FONT_SIZE)
# MAIN_FONT = 'helvetica {}'.format(MAIN_FONT_SIZE)
# MAIN_BOLD_FONT = 'helvetica {} bold'.format(MAIN_SMALL_FONT_SIZE)
# MAIN_MID_FONT = 'helvetica {}'.format(MAIN_MID_FONT_SIZE)
# MAIN_LARGE_FONT = 'helvetica {}'.format(MAIN_ULTRA_FONT_SIZE)
MAIN_SMALL_FONT = ('helvetica', MAIN_SMALL_FONT_SIZE)
MAIN_FONT = ('helvetica', MAIN_FONT_SIZE)
MAIN_BOLD_FONT = ('helvetica bold', MAIN_SMALL_FONT_SIZE)
MAIN_MID_FONT = ('helvetica', MAIN_MID_FONT_SIZE)
MAIN_LARGE_FONT = ('helvetica', MAIN_ULTRA_FONT_SIZE)

BUTTON_BORDER_COLOR = "black"
BUTTON_TEXT_COLOR = "white"
BUTTON_FG_COLOR = MAIN_COLOR_LIGHT
BUTTON_HOVER_COLOR = MAIN_COLOR_DARK
BUTTON_SIZE_0_HEIGHT = 32
BUTTON_SIZE_0_WIDTH = 60
BUTTON_SIZE_0_FONT_SIZE = MAIN_FONT_SIZE
BUTTON_SIZE_0_CORNER_RADIUS = 5

BUTTON_SIZE_1_HEIGHT = 32
BUTTON_SIZE_1_WIDTH = 100
BUTTON_SIZE_1_FONT_SIZE = MAIN_MID_FONT_SIZE
BUTTON_SIZE_1_CORNER_RADIUS = 10

BUTTON_SIZE_3_HEIGHT = 60
BUTTON_SIZE_3_WIDTH = 120
BUTTON_SIZE_3_FONT_SIZE = MAIN_LARGE_FONT_SIZE
BUTTON_SIZE_3_CORNER_RADIUS = 15

CHECK_BUTTON_FG_COLOR = MAIN_COLOR_LIGHT
CHECK_BUTTON_HOVER_COLOR = MAIN_COLOR_DARK
CHECKMARK_COLOR = "black"

DROPDOWN_MENU_TEXT_COLOR = "white"
DROPDOWN_TEXT_COLOR = "white"
DROPDOWN_COLOR = "grey"
DROPDOWN_MENU_WIDTH = 40
DROPDOWN_MENU_HOVER_COLOR = MAIN_COLOR_DARK
DROPDOWN_MENU_BUTTON_COLOR = MAIN_COLOR_DARK
DROPDOWN_MENU_FG_COLOR = MAIN_COLOR_LIGHT

ENTRY_HIGHLIGHT_COLOR = MAIN_COLOR_LIGHT

BORDERED_FRAME_HIGHLIGHT_THICKNESS = 1
BORDERED_FRAME_BORDER_COLOR = MAIN_COLOR_LIGHT

CIRCULAR_BUTTON_FONT_SIZE = MAIN_MID_FONT_SIZE
CIRCULAR_BUTTON_WIDTH = 50
CIRCULAR_BUTTON_HEIGHT = 80
# CIRCULAR_BUTTON_WIDTH = 30
# CIRCULAR_BUTTON_HEIGHT = 40

LABEL_2_FONT = MAIN_LARGE_FONT
LABEL_1_FONT = MAIN_MID_FONT
LABEL_0_FONT = MAIN_FONT
LABEL_BOLD_FONT = MAIN_BOLD_FONT
TABLE_NORMAL_FONT = MAIN_SMALL_FONT

MESSAGEBOX_FONT = MAIN_FONT

BACK_AND_PLUS_SECONDS = 5
ANALYZER_TIMELINE_THICKNESS = 18
ANALYZER_MARKER_THICKNESS = 20
TIMER_MARKER_THICKNESS = 30
TIMER_TIMELINE_THICKNESS = 20

COLOR_THEME = {'blue': '#4581ec',
                'red': '#ef5c57',
                'yellow': '#efad4d',
                'black': '#343a41',
                'green': '#04b876',
                'aquamarine': '#17a3b8',
                'darkpurple': '#534050',
                'brown': '#954535'}